### ISSUE TITLE
Document how to run a Java (xlang) pipeline on the Spark portable runner

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20224] opened 2022-06-04 16:19 UTC
While users will probably still prefer the classic Spark runner for most Java pipelines, the Spark portable runner enables cross-language transforms. We can start by providing instructions for plain Java, then add cross-language (Java -\> Python).

Imported from Jira [BEAM-10151](https://issues.apache.org/jira/browse/BEAM-10151). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by mosche** [comment] 2022-10-21 14:42
Duplicate of https://github.com/apache/beam/issues/20224

**Closed by mosche** 2022-10-21 14:42 UTC
Labels: website, runners, spark, portability, new feature, P3, cross-language
