### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21585] opened 2022-06-05 00:26 UTC
Support for Python 3.10

Imported from Jira [BEAM-14126](https://issues.apache.org/jira/browse/BEAM-14126). Original Jira may contain additional context.
Reported by: Anand Inguva.

**Comment by nharada1** [comment] 2022-06-26 01:53
Is Beam going to get Python 3.10 support in the near term? More broadly, how soon does Beam aim to support new Python releases?

**Comment by kennknowles** [comment] 2022-06-27 03:51
@AnandInguva if I recall, you were considering working on this
/cc @tvalentyn

**Comment by AnandInguva** [comment] 2022-06-27 03:54
Yes, its in progress. It's blocked on few type hint related things.

**Comment by AnandInguva** [comment] 2022-06-27 03:56
@tvalentyn can add more pointers on the release dates.

**Comment by AnandInguva** [comment] 2022-07-27 14:36
@tvalentyn @damccorm Would you be able to close this? This is a duplicate of https://github.com/apache/beam/issues/21458

**Comment by damccorm** [comment] 2022-07-27 14:39
Sure - you can also close it with chat commands:

.close-issue

**Comment by AnandInguva** [comment] 2022-07-27 14:40
Closing this as this is a duplicate of #21458 

.close-issue

**Comment by AnandInguva** [comment] 2022-07-27 14:41
.close-issue

**Comment by damccorm** [comment] 2022-07-27 14:42
(GitHub Actions are a little backed up right now, so it might take a little while - see the queue here https://github.com/apache/beam/actions)

**Closed** 2022-07-27 15:31 UTC
Labels: python, core, improvement, P2
