### ISSUE TITLE
[Bug]: [TextIO] Prevent threads from hanging indefinitely

### ISSUE THREAD

**Issue by bvolpato** [apache/beam#27395] opened 2023-07-07 17:56 UTC
### What happened?

Recently observed the case where TextIO / WriteFiles was hanging indefinitely on `@FinishBundle`:

https://github.com/apache/beam/blob/release-2.48.0/sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java#L1021-L1034

We are doing `MoreFutures.get(MoreFutures.allAsList(closeFutures))`, and for some reason, threads are not completing.

I believe we should investigate adding a reasonable timeout (`MoreFutures.get(MoreFutures.allAsList(closeFutures), 1, TimeUnit.HOURS)`?) to avoid having jobs hanging forever. The work will be retried, so it shouldn't cause any data loss.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment] 2024-12-06 00:02
Closing as duplicate of  https://github.com/apache/beam/issues/29926

**Closed by tvalentyn** 2024-12-06 00:02 UTC
Labels: java, bug, P2, awaiting triage
