### ISSUE TITLE
[Bug][Prism]: panic: unsupported StateKey Get type: *fnexecution_v1.StateKey_MultimapKeysSideInput_

### ISSUE THREAD

**Issue by damondouglas** [apache/beam#31339] opened 2024-05-17 21:32 UTC
Java test `org.apache.beam.sdk.transforms.ViewTest` fails on Prism with error `panic: unsupported StateKey Get type: *fnexecution_v1.StateKey_MultimapKeysSideInput_`:

Full error:
```
panic: unsupported StateKey Get type: *fnexecution_v1.StateKey_MultimapKeysSideInput_: multimap_keys_side_input:  {
  transform_id:  "OutputSideInputs-ParMultiDo-Anonymous-"
  side_input_id:  "org.apache.beam.sdk.values.PCollectionViews$SimplePCollectionView.<init>:1443#bbafda9391edc490"
}
```

Steps to reproduce.

1) Run Prism server.

```
./gradlew :runners:prism:runServer
```

2) Execute `:runners:portability:java:ulrLoopbackValidatesRunnerTests` on Prism:

```
TEST=org.apache.beam.sdk.transforms.ViewTest
./gradlew :runners:portability:java:ulrLoopbackValidatesRunnerTests -PjobEndpoint=localhost:8073 --tests="$TEST"
```

Parent tracker: #28187

**Comment by lostluck** [comment] 2024-07-02 22:39
I think that this was handled in #31632 and is a duplicate of #31628. Closing.

**Closed by lostluck** 2024-07-02 22:39 UTC
Labels: go, bug, P2, prism
