### ISSUE TITLE
[Task]: Change KinesisTransformRegistrar.java to use amazon-web-services2 package instead of the amazon-web-services.

### ISSUE THREAD

**Issue by vishwesh0409** [apache/beam#27615] opened 2023-07-22 07:44 UTC
### What needs to happen?

The amazon-web-services package is depricated and gives java null pointer errors when running the KinesisIO read ptransform. 

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by mosche** [comment] 2023-07-26 08:13
Looks like a duplicate of #23570, I suppose you are running an x-lang pipeline?

**Comment by vishwesh0409** [comment] 2023-07-26 10:45
Yes. 

> Looks like a duplicate of #23570, I suppose you are running an x-lang pipeline?

Yes

**Closed** 2023-08-01 16:08 UTC
Labels: java, P3, task, awaiting triage
