### ISSUE TITLE
404s in BigQueryIO don't get output to Failed Inserts PCollection

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21713] opened 2022-06-05 01:25 UTC
Given that BigQueryIO is configured to use createDisposition(CREATE_NEVER),
and the DynamicDestinations class returns "null" for a schema,
and the table for that destination does not exist in BigQuery, When I stream records to BigQuery for that table, then the write should fail,
and the failed rows should appear on the output PCollection for Failed Inserts (via getFailedInserts().
 
Almost all of the time, the table exists before hand, but given that new tables can be created, we want this behavior to be non-explosive to the Job, however, what we are seeing is that processing completely stops in those pipelines, and eventually the jobs run out of memory. I feel that the appropriate action when BigQuery 404's for the table, would be to submit those failed TableRows to the output PCollection and continue processing as normal.

Imported from Jira [BEAM-14364](https://issues.apache.org/jira/browse/BEAM-14364). Original Jira may contain additional context.
Reported by: svetak.

**Comment by damccorm** [comment] 2022-06-05 01:25
Unable to assign user @svetakvsundhar. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by kennknowles** [comment] 2022-09-13 23:06
@reuvenlax @johnjcasey is this still happening? There is a lot of context on the Jira comments that I haven't brought over. It sounds like fundamental bugs in the connector.

**Comment by reuvenlax** [comment] 2022-09-14 05:45
I suspect it does happen. Some context:
This feature was intended for known persistent failures at the row level, and is implemented using the per-row status returned by BigQuery. An example would be a row that does not match the BigQuery schema or a row that exceeds BigQuery's size limit. This feature does not capture potentially ephemeral failures, such as when the RPC to BigQuery itself fails. In that case we simply retry the RPC.

While it seems that the RPC returning a 404 is a persistent error, this generally isn't the case. For instance a temporary outage might cause the RPC to return 404, yet on retry the RPC succeeds. We didn't want a situation in which a temporary BigQuery outage caused all data to be sent to the dead-letter output for a period of time.

However I would like to understand the use case more. Is this a case in which records destined for a specific table are sent to the Dataflow pipeline before the BigQuery table is created? Is there some offline process creating those tables, and is that process simply delayed?

**Comment by johnjcasey** [comment] 2022-09-14 15:04
@svetakvsundhar are you still looking at this?

**Comment by johnjcasey** [comment] 2022-09-19 15:36
Is there a particular reason to not use a pattern of outputting to failure after N retries?

**Comment by reuvenlax** [comment] 2022-09-19 16:09
In general, that pattern is avoided in streaming, since the system
prioritizes data consistency. Temporary problems (e.g. temporary issues
with the sink, the network, or anything else) could easily cause N retries
to exceed, causing 100% of output going to the failure collection.

A second issue is that there isn't a good way of determining retry count.
We can only know retry count in the current bundle. If the bundle fails and
retries, our count gets set back to 0.

**Comment by kennknowles** [comment] 2023-03-23 21:38
Based on all of this, I think we can close this as working as intended.

**Closed by kennknowles** 2023-03-23 21:38 UTC
Labels: python, io, gcp, P1, bug
