### ISSUE TITLE
[Bug]: use_grpc_for_gcs experiment broken by big dataoss library upgrade from 2.2.6 to 2.2.8

### ISSUE THREAD

**Issue by lukecwik** [apache/beam#23588] opened 2022-10-11 23:03 UTC
### What happened?

The `use_grpc_for_gcs` experiment was broken by the upgrade of the big dataoss library from 2.2.6 to 2.2.8 (https://github.com/apache/beam/pull/23300) and was caught by internal testing within Google (b/251766179).

I used the following flags when creating the pipeline:
```
--experiments=use_grpc_for_gcs --gcsUploadBufferSizeBytes=16777216
```

The pipeline fails to upload artifacts during pipeline creation. An example dump of the failure is below:
```
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
Oct 11, 2022 3:39:58 PM org.apache.beam.runners.dataflow.DataflowRunner fromOptions
INFO: PipelineOptions.jobName did not match the service requirements. Using df2-source-bench-text-100g-staging-10111534327073 instead of df2-source-bench-text-100G-staging-10111534327073.
Oct 11, 2022 3:39:59 PM org.apache.beam.runners.dataflow.DataflowRunner run
INFO: Executing pipeline on the Dataflow Service, which will have billing implications related to Google Compute Engine usage and other Google Cloud Services.
Oct 11, 2022 3:40:00 PM org.apache.beam.runners.dataflow.util.PackageUtil stageClasspathElements
INFO: Uploading 2 files from PipelineOptions.filesToStage to staging location to prepare for execution.
Oct 11, 2022 3:40:00 PM org.apache.beam.runners.dataflow.util.PackageUtil tryStagePackage
INFO: Uploading /usr/local/google/_blaze_lcwik/1fc426c8a75c8141859a9e8595f2fd0a/execroot/google3/blaze-out/k8-opt/bin/cloud/dataflow/testing/integration/perf/source_bench_text_100G_gcs_with_grpc.runfiles/google3/cloud/dataflow/testing/framework/options/conscrypt.jar to gs://deft-guitar-sandbox-e2e-test/df2-source-bench-text-100G-staging/10111534327072/staging/lcwik/conscrypt-AfnHQstZKhUeLmK9U5eomAYoqWcAH82s1KpHRGeGhfM.jar
Oct 11, 2022 3:40:00 PM org.apache.beam.runners.dataflow.util.PackageUtil tryStagePackage
INFO: Uploading /usr/local/google/_blaze_lcwik/1fc426c8a75c8141859a9e8595f2fd0a/execroot/google3/blaze-out/k8-opt/bin/cloud/dataflow/testing/integration/perf/source_bench_text_100G_gcs_with_grpc.runfiles/google3/javatests/com/google/cloud/dataflow/v2/beam-testing-bundle.jar to gs://deft-guitar-sandbox-e2e-test/df2-source-bench-text-100G-staging/10111534327072/staging/lcwik/beam-testing-bundle-VMTQVJGM2Ldw1dAThX5bn1C7UwZoBdhVhq6XD-GXCHU.jar
Oct 11, 2022 3:43:00 PM org.apache.beam.runners.dataflow.util.PackageUtil stageClasspathElements
INFO: Still staging 2 files
Oct 11, 2022 3:46:00 PM org.apache.beam.runners.dataflow.util.PackageUtil stageClasspathElements
INFO: Still staging 2 files
Oct 11, 2022 3:46:11 PM com.google.cloud.hadoop.util.ResilientOperation nextSleep
INFO: Transient exception caught. Sleeping for 710, then retrying.
java.io.IOException: Got transient error for UploadID 'ADPycdtUrXxAYd3LoEhcLfF-VNMfY2kvwpyIzERGjfcVAaDWbGF7Ep1We5NSt0n9gJiLc7MxBGcZgSv5WwfjyKRgK87Ekw'
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.doResumableUpload(GoogleCloudStorageGrpcWriteChannel.java:325)
	at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:66)
	at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:105)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.call(GoogleCloudStorageGrpcWriteChannel.java:206)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.call(GoogleCloudStorageGrpcWriteChannel.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: 408:Request Timeout
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.census.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:802)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.census.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:436)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more

Oct 11, 2022 3:49:00 PM org.apache.beam.runners.dataflow.util.PackageUtil stageClasspathElements
INFO: Still staging 2 files
Oct 11, 2022 3:52:00 PM org.apache.beam.runners.dataflow.util.PackageUtil stageClasspathElements
INFO: Still staging 2 files
Oct 11, 2022 3:52:20 PM com.google.cloud.hadoop.util.ResilientOperation nextSleep
INFO: Transient exception caught. Sleeping for 580, then retrying.
java.io.IOException: Got transient error for UploadID 'ADPycdtUrXxAYd3LoEhcLfF-VNMfY2kvwpyIzERGjfcVAaDWbGF7Ep1We5NSt0n9gJiLc7MxBGcZgSv5WwfjyKRgK87Ekw'
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.doResumableUpload(GoogleCloudStorageGrpcWriteChannel.java:325)
	at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:66)
	at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:105)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.call(GoogleCloudStorageGrpcWriteChannel.java:206)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.call(GoogleCloudStorageGrpcWriteChannel.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: 408:Request Timeout
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.census.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:802)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.census.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:436)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
```

### Issue Priority

Priority: 0

### Issue Component

Component: io-java-gcp

**Comment by lukecwik** [comment] 2022-10-11 23:04
CC: @scwhittle @damccorm

**Comment by lostluck** [comment] 2022-10-11 23:19
I'll note that if it's an experiment, it shouldn't be release blocking, as that's what experiment means.

That said, we're already collecting things for an RC2, so we may as well fix it.

**Comment by lostluck** [comment] 2022-10-11 23:34
Assigning to [scwhittle](https://github.com/scwhittle) since I'm a vocal Go programmer and can't make heads or tails of Java Deps.

But I can't assign it to scwhittle unless they comment here first. :/

**Comment by lostluck** [comment] 2022-10-11 23:37
Is that PR even in the release? The release was cut on the 7th but the PR was merged on the 20th.

**Comment by lostluck** [comment] 2022-10-12 00:00
It is not (validated with `git branch --contains 5af5a1fb2016ab62387de5973c5a8ed0ec3045fd`).

Changing the milestone to 2.43.0

**Comment by chamikaramj** [comment] 2022-10-12 01:10
@scwhittle will you be able to check ?

Also cc'ing few folks who might have context/interest. @cnauroth @medb @veblush

**Comment by cnauroth** [comment] 2022-10-12 01:49
Between GCS connector 2.2.6 and 2.2.8, there were multiple changes in the gRPC integration path. I haven't yet identified a specific change that could explain this.

CC: @abmodi @arunkumarchacko

**Comment by arunkumarchacko** [comment] 2022-10-12 04:23
There is a know issue where uploads of more than 30MB is failing. This is due to a change at the GCS side.

CC: @singhravidutt

**Comment by scwhittle** [comment] 2022-10-12 07:25
I don't think I'm the right person to investigate this, I upgraded the version to fix a Conscrypt issue but don't have any other relevant knowledge.
It sounds like Chris is investigating from above

**Comment by chamikaramj** [comment] 2022-10-12 21:18
Thanks Sam. @arunkumarchacko do you have a reference to that issue ?

If that is fixed and released, probably we can just do another version bump.

**Comment by arunkumarchacko** [comment] 2022-10-13 14:49
What is the impact at your side? This will help us prioritise. Also, gRPC support in GCS is not yet GA. Hence was wondering how you are using this.

Also, can you try with a lower upload size? If you are hitting the same issue, it usually happens when the upload size is higher (more than 30MB). This will also help us confirm that that it is the same issue.

**Comment by lukecwik** [comment] 2022-10-13 18:51
This will break customers who are opted into the experiment that rely on the SDK at HEAD and will block the 2.43 release which will be cut on Oct 19, 2022.

Are you talking about the whole file size or the buffer size (note that I tested with 16mb buffer and it was failing)?
If it is for the whole file size then we can't reduce it since almost all customer pipelines use files that are greater than 30 mbs.

**Comment by chamikaramj** [comment] 2022-10-17 18:23
@johnjcasey can you determine if this should be a blocker for the Beam 2.43.0 release ?

If the fix is purely on the GCS client library side, I don't think we should block the Beam release on this.

I'm not sure if the workaround mentioned above apply to Beam BTW. "fs.gs.grpc.write.buffered.requests" seems like a Hadoop configuration option that does not apply to Beam. Not sure if changing the Beam write buffer size will result in a similar workaround.

**Comment by johnjcasey** [comment] 2022-10-18 14:38
The fix may be in the libraries, but as long as we have a broken version of the library imported, I think this would could block the release. It would mean that users of use_grpc_for_gcs couldn't use 2.43. As such, I think this blocks the release, unless our policy is that it is fine for experiments to break for a version. @lukecwik @chamikaramj what is the standard here?

**Comment by lukecwik** [comment] 2022-10-18 18:46
Typically rollback so that issues that were resolved are re-opened and those users will continue to have the same experience and we don't break anyone effectively deferring the fix.

Users who need the newer version of the library can choose to override the dependency version to 2.2.8 knowing that they get the fixes OR can use the experiment, not both.

**Comment by chamikaramj** [comment] 2022-10-18 18:56
I'm in favor of rolling back the original dependency upgrade (https://github.com/apache/beam/pull/23300).

Also, IIUC, Dataflow runner does not use the Conscrypt security provider by default unless experiment enable_conscrypt_security_provider is used (dependency upgrade was intended to fix an issue with Conscrypt).

Any affected users could manually upgrade the bigdataoss:gcsio library as Luke mentioned.

@scwhittle are you ok with that ?

**Comment by scwhittle** [comment] 2022-10-18 19:04
Yes, that is fine to rollback, we can instruct them to upgrade the dependency themselves.

**Comment by johnjcasey** [comment] 2022-10-19 15:03
created a rollback PR

**Comment by chamikaramj** [comment] 2022-10-19 16:29
Sounds good. Thanks.

**Closed** 2022-10-20 15:23 UTC
Labels: java, io, gcp, bug, P0

**Comment by scwhittle** [comment] 2022-11-22 20:17
@arunkumarchacko Was the grpc issue in the bigdataoss fixed in a later bigdataoss version? I took a quick look but didn't see an issue, is there one? Thanks!

**Comment by clairemcginty** [comment] 2023-03-08 16:53
hi @lukecwik! I was wondering if there was any update on this. I noticed that the dependency on bigdataoss 2.2.6 is pulling in [outdated api-services libraries](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v2.2.6/pom.xml#L87) relative to the rest of Beam, which uses api-client version 2.0.0+.

**Comment by johnjcasey** [comment] 2023-03-09 15:29
We are still on 2.2.6, thought it looks like version 2.2.11 is available. Luke no longer works on beam, however. I've raised #25777 to track this

**Comment by bvolpato** [comment] 2023-07-26 13:58
Attempting a new upgrade https://github.com/apache/beam/pull/27679

gcsio 2.2.16 uses api-client 2.x, which will handle the concerns here.
