### ISSUE TITLE
Docker Snapshots failing to be published since April 14th

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21698] opened 2022-06-05 01:21 UTC
https://ci-beam.apache.org/job/beam_Publish_Docker_Snapshots/

13:50:44 \> Task :sdks:go:container:docker FAILED
13:50:44 ADD failed: stat /var/lib/docker/tmp/docker-builder845277900/target/linux_amd64/boot: no such file or directory

Started in https://ci-beam.apache.org/job/beam_Publish_Docker_Snapshots/585/ or https://ci-beam.apache.org/job/beam_Publish_Docker_Snapshots/586/

Imported from Jira [BEAM-14459](https://issues.apache.org/jira/browse/BEAM-14459). Original Jira may contain additional context.
Reported by: lostluck.

**Comment by lostluck** [comment] 2022-06-28 20:37
Looks like the lack of built containers has caught up with us since we've made breaking changes to the container version.

SDK containers haven't been built in some time, and the breaking change has broken Load Test metrics gathering. 
http://metrics.beam.apache.org/d/UYZ-oJ3Zk/gbk-load-tests?orgId=1&var-processingType=batch&var-sdk=go

**Comment by lostluck** [comment] 2022-06-29 19:08
But first, lets just try using tagPush in this task instead of throwing everything away...

**Comment by lostluck** [comment] 2022-06-29 22:00
No difference. Moving forward with removing Go from this publishing, and switching the load tests to use the snapshots that are actually published. AFAICT there's no meaningful difference between the two tasks that should cause the Docker build to fail this way, so it's perplexing to me.

Confirmed moving to the normal snapshot containers fixes the load tests on Dataflow, while Flink remains busted.

**Closed** 2022-06-30 16:39 UTC
Labels: go, P1, bug, flaky
