### ISSUE TITLE
ElasticsearchIO: Enabling both User/Pass auth and SSL overwrites User/Pass

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21088] opened 2022-06-04 21:34 UTC
When using the ElasticsearchIO class in the SDK, if you enable both username and password auth AND SSL, the SSL addition overwrites the username and password credentials as both utilize .setHttpClientConfigCallback() 
See: [https://github.com/apache/beam/blob/4fb05beb4b1063388432d4a66aa4ea245542cb02/sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java#L599](https://github.com/apache/beam/blob/4fb05beb4b1063388432d4a66aa4ea245542cb02/sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java#L599)

To recreate, set both the user/pw and keystore info for the write/read transform.  Authentication then fails when connecting to an SSL****user/pw auth cluster.

Imported from Jira [BEAM-12632](https://issues.apache.org/jira/browse/BEAM-12632). Original Jira may contain additional context.
Reported by: dboshardy.

**Comment by egalpin** [comment] 2022-08-25 16:32
Fixed by #17297 (duplicate of BEAM-14000)

**Closed by egalpin** 2022-08-25 16:32 UTC
Labels: java, io, elasticsearch, P3, bug
