### ISSUE TITLE
[Bug]: Incorrect address after clicking on the "Get Started"

### ISSUE THREAD

**Issue by alevtinaboiko** [apache/beam#22523] opened 2022-07-29 07:05 UTC
### What happened?

Steps:

1. Open the website 
2. Click on the button "Get Started" in the navbar

Actual result: After clicking on the button "Get started" the page "https://beam.apache.org/get-started/beam-overview/" opens
Expected result: After clicking on the button "Get started" the page https://beam.apache.org/get-started  opens

### Issue Priority

Priority: 1

### Issue Component

Component: beam-model

**Comment by bullet03** [comment] 2022-07-29 15:34
.take-issue

**Comment by rszper** [comment] 2022-10-07 19:13
This is a duplicate of https://github.com/apache/beam/issues/21537

There already a PR with a fix: https://github.com/apache/beam/pull/23490

**Comment by rszper** [comment] 2023-07-24 22:49
.close-issue

**Closed** 2023-07-24 22:49 UTC
Labels: bug, documentation, P2
