### ISSUE TITLE
testTeardownCalledAfterExceptionInProcessElement flakes on direct runner.

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20815] opened 2022-06-04 19:50 UTC
https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/15307/testReport/junit/org.apache.beam.sdk.transforms/ParDoLifecycleTest/testTeardownCalledAfterExceptionInProcessElement/

java.lang.AssertionError: Function should have been torn down after exception
Expected: is <TEARDOWN\>
     but: was <START_BUNDLE\>

Imported from Jira [BEAM-11541](https://issues.apache.org/jira/browse/BEAM-11541). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by kennknowles** [comment] 2022-10-21 01:32
According to https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Direct/test_results_analyzer/ this has not flaked in 100 runs. I also could not reproduce. It is not disabled so we can just close this.

**Closed by kennknowles** 2022-10-21 01:32 UTC
Labels: java, runners, direct, P1, bug, failing test, flake
