### ISSUE TITLE
[Bug]: SizeLimitExceededException thrown while sending a small message to GCP PubSub

### ISSUE THREAD

**Issue by jkosternl** [apache/beam#27178] opened 2023-06-20 14:57 UTC
### What happened?

Since Beam v2.48 (Java), there is a bug introduced in the logic that verifies the total size of the message send to PubSub. The message size is checked against the amount of messages inside a batch (100). In v2.47 and before this was working fine. 

**Effect of the bug**
Currently, in v2.48, it is not possible to use `PubsubIO` class to send messages to GCP PubSub from a Pipeline. It will cause a SizeLimitExceededException thrown like this:
"Pubsub message of length XXX exceeds maximum of 100 bytes, when considering the payload and attributes. See https://cloud.google.com/pubsub/quotas#resource_limits "

**Cause**
The bug is caused by [commit](https://github.com/apache/beam/commit/f549fd33abdc672143ccbe3f0f66104995d30fe6#diff-f4e5c47f68991f7d2820a6c94ce7bb5dc1568ea58eb1e8480d41c8ef4805f6ff) specifically file `sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PreparePubsubWriteDoFn.java` at line 100, committed by @reuvenlax 

**Solution**
In Beam v2.47, a similar check was performed against `maxPublishBatchByteSize` in file `PubsubIO` which is totally fine. So, please use the idea of comparing bytes with bytes, as was done there. 

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by chamikaramj** [comment] 2023-06-22 18:34
This seems like a regression for 2.48.0 caused by https://github.com/apache/beam/pull/26063. @reuvenlax can you check ?

**Comment by chamikaramj** [comment] 2023-06-22 18:35
Also making this a blocker for the 2.49.0 release.

**Comment by chamikaramj** [comment] 2023-06-22 18:37
Ah, seems like it was already fixed: https://github.com/apache/beam/issues/27000

Closing this issue. Please re-open if the issue was not addressed by the above.

**Closed by chamikaramj** 2023-06-22 18:37 UTC
Labels: java, P1, bug

**Comment by jkosternl** [comment] 2023-06-22 19:37
Ah yes, you're right. I didn't find that bug while searching, unfortunately. Thanks @chamikaramj
