### ISSUE TITLE
Bump spark3 dependencies to 3.2.1

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21291] opened 2022-06-04 22:37 UTC
Imported from Jira [BEAM-13891](https://issues.apache.org/jira/browse/BEAM-13891). Original Jira may contain additional context.
Reported by: aromanenko.

**Comment by mosche** [comment] 2022-07-06 04:49
Related to https://github.com/apache/beam/issues/22156

**Comment by mosche** [comment] 2022-10-25 16:15
Duplicate of #23804

**Closed by mosche** 2022-10-25 16:15 UTC
Labels: runners, spark, dependencies, P3, improvement
