### ISSUE TITLE
[Bug]: Regression issue when reading compressed Avro files using AvroIO

### ISSUE THREAD

**Issue by carlpayne** [apache/beam#25794] opened 2023-03-10 16:10 UTC
### What happened?

We recently upgraded some of our Beam pipelines from `2.34.0` to `2.45.0` (latest at the time of writing). After doing so, we noticed that some of our batch jobs that read compressed (gzip) Avro files are now failing. I've created a repository [here](https://github.com/carlpayne/beam-demo) with a working example of how to reproduce, but will include the steps below.

First, checkout the [sample repository](https://github.com/carlpayne/beam-demo)

## Apache Beam 2.34.0
The demo works as expected using this version of Apache Beam. To demonstrate:

1. First ensure `def beam_version = "2.34.0"` is set in `build.gradle` (it should be the default on a fresh git clone)
2. ```./gradlew run```

Notice that the code outputs the expected "tweet" contents by reading the zipped Avro files:

```
TWEET: User: migunoTweet: Rock: Nerf paper, scissors is fine.
TWEET: User: migunoTweet: Rock: Nerf paper, scissors is fine.
TWEET: User: BlizzardCSTweet: Works as intended.  Terran is IMBA.
TWEET: User: BlizzardCSTweet: Works as intended.  Terran is IMBA.
```

## Apache Beam 2.45.0
With later versions of Apache Beam, we see unexpected failures with the same code. To demonstrate:

1. First comment out `def beam_version = "2.34.0"` in `build.gradle`
2. Un-comment `def beam_version = "2.45.0"`
3. ```./gradlew run```

Notice that the code fails with the following stack trace:

```
> Task :run FAILED
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.ClassCastException: class java.nio.channels.Channels$ReadableByteChannelImpl cannot be cast to class java.nio.channels.SeekableByteChannel (java.nio.channels.Channels$ReadableByteChannelImpl and java.nio.channels.SeekableByteChannel are in module java.base of loader 'bootstrap')
        at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:374)
        at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
        at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:218)
        at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:323)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:309)
        at beam.demo.Demo.main(Demo.java:52)
Caused by: java.lang.ClassCastException: class java.nio.channels.Channels$ReadableByteChannelImpl cannot be cast to class java.nio.channels.SeekableByteChannel (java.nio.channels.Channels$ReadableByteChannelImpl and java.nio.channels.SeekableByteChannel are in module java.base of loader 'bootstrap')
        at org.apache.beam.sdk.io.AvroSource$AvroReader.startReading(AvroSource.java:743)
        at org.apache.beam.sdk.io.CompressedSource$CompressedReader.startReading(CompressedSource.java:449)
        at org.apache.beam.sdk.io.FileBasedSource$FileBasedReader.startImpl(FileBasedSource.java:479)
        at org.apache.beam.sdk.io.OffsetBasedSource$OffsetBasedReader.start(OffsetBasedSource.java:252)
        at org.apache.beam.sdk.io.ReadAllViaFileBasedSource$ReadFileRangesFn.process(ReadAllViaFileBasedSource.java:140)
```

## Compressed vs Un-compressed Avro Files
One important point worth noting is that this issue only seems to occur for compressed files. If we read in the un-compressed versions then the code works as expected. To demonstrate:
1. Update `Demo.java` so that `LinkedList<String> files` reads in `"twitter1.avro"` and `"twitter1.avro"`, instead of the compressed versions
2. ```./gradlew run```

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [x] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by aromanenko-dev** [comment] 2023-03-13 14:54
Did you try to reproduce it with other Beam versions between 2.34.0 and 2.45.0?

**Comment by carlpayne** [comment] 2023-03-13 15:22
@aromanenko-dev great question! I just did some further testing, with the following results:

| Beam Version  | Result |
| ------------- | ------------- |
| 2.34.0  | ✅ |
| 2.35.0  | ✅ |
| 2.36.0  | ✅ |
| 2.37.0  | ✅ |
| 2.38.0  | ✅ |
| 2.39.0  | ✅ |
| 2.40.0  | ✅ |
| 2.41.0  | ✅ |
| 2.42.0  | ✅ |
| 2.43.0  | ❌ |
| 2.44.0  | ❌|
| 2.45.0  | ❌ |
| 2.46.0  | ❌ |

So, it seems the regression first came in with `2.43.0`. My guess is that perhaps [this](https://github.com/apache/beam/commit/a6cda1370b31dfd585c37c5066b89c4498158793#diff-7bb94a476b713856a79e36e38e680d580f12b9060e8e3a613b74137bc5f5c9c2) change might be the cause, as it was introduced during `2.43.0` and is the first time we see `SeekableChannelInput`, which appears in the stacktrace I added previously when dealing with zipped files.

**Comment by aromanenko-dev** [comment] 2023-03-13 17:03
Great, thank you for checking this! Yes, it seems that it might caused by this change...

Ping @steveniemitz as an author of that PR. Could you help us with this?

**Comment by steveniemitz** [comment] 2023-03-16 14:41
I think the issue is that beam is trying to decompress the `.gz` suffixed file, even though its not actually gzipped.  When you do `FileIO.readMatches` you can try using [withCompression(Compression.UNCOMPRESSED)](https://beam.apache.org/releases/javadoc/2.45.0/org/apache/beam/sdk/io/FileIO.ReadMatches.html#withCompression-org.apache.beam.sdk.io.Compression-) to disable the automatic decompression.

**Comment by steveniemitz** [comment] 2023-03-16 14:59
It's not a tar file either, its just a normal avro file with a `gz` extension.  The fact that it worked before was really an accident because the old avro reader before my change ignored the channel that beam was passing it.

The best fix is to do what I described above and tell `FileIO.readMatches` to not attempt to decompress the files.

**Comment by aromanenko-dev** [comment] 2023-03-16 15:05
@steveniemitz Thanks but iiuc it fails exactly while reading **compressed** Avro files. @carlpayne could you confirm?

**Comment by aromanenko-dev** [comment] 2023-03-16 15:18
@carlpayne Great that it helped! Can we close this issue then?

**Comment by Abacn** [comment] 2023-03-16 15:18
I compressed the .avro and the problem still exists:
```
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.ClassCastException: class java.nio.channels.Channels$ReadableByteChannelImpl cannot be cast to class java.nio.channels.SeekableByteChannel (java.nio.channels.Channels$ReadableByteChannelImpl and java.nio.channels.SeekableByteChannel are in module java.base of loader 'bootstrap')
        at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:374)
        at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
        at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:218)
        at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:323)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:309)
        at beam.demo.Demo.main(Demo.java:59)
Caused by: java.lang.ClassCastException: class java.nio.channels.Channels$ReadableByteChannelImpl cannot be cast to class java.nio.channels.SeekableByteChannel (java.nio.channels.Channels$ReadableByteChannelImpl and java.nio.channels.SeekableByteChannel are in module java.base of loader 'bootstrap')
        at org.apache.beam.sdk.io.AvroSource$AvroReader.startReading(AvroSource.java:743)
        at org.apache.beam.sdk.io.CompressedSource$CompressedReader.startReading(CompressedSource.java:449)
        at org.apache.beam.sdk.io.FileBasedSource$FileBasedReader.startImpl(FileBasedSource.java:479)
        at org.apache.beam.sdk.io.OffsetBasedSource$OffsetBasedReader.start(OffsetBasedSource.java:252)
        at org.apache.beam.sdk.io.ReadAllViaFileBasedSource$ReadFileRangesFn.process(ReadAllViaFileBasedSource.java:140)

```

**Comment by steveniemitz** [comment] 2023-03-16 15:18
💥 good to hear! The only thing I could think of doing here to fix it would be to re-open the files in the reader explicitly without decompression, but doing so breaks the source/reader abstraction.  

This isn't really specific to the avro IO either, other IOs would have similar issues.  It'd be nice if the source API had a way to communicate to the FileBasedSource that it didn't want automatic decompression when opening the channel, but I don't think it does right now.

**Comment by steveniemitz** [comment] 2023-03-16 15:32
Yeah beam never had the ability to process full-file compressed avro files, you'd need to decompress them first to a temp location and them read those.  If you want compression you should use the built-in compression support that the avro container file presents.  If you're using beam that'd be [withCodec](https://beam.apache.org/releases/javadoc/2.45.0/org/apache/beam/sdk/io/AvroIO.TypedWrite.html#withCodec-org.apache.avro.file.CodecFactory-) on AvroIO.

**Comment by aromanenko-dev** [comment] 2023-03-16 15:44
Ok, I'm closing this one since it's not a regression.
Thanks everybody for chasing this issue!

**Closed by aromanenko-dev** 2023-03-16 15:44 UTC
Labels: java, io, P3, bug, avro
